FROM node:16.10-alpine as builder

RUN mkdir -p /app
WORKDIR /app

COPY . .

RUN npm install \
    && npm run build \
    && cd build \
    && npm ci --production

FROM node:16.10-alpine

RUN mkdir -p /app
WORKDIR /app

COPY --from=builder "/app/build" "/app"

CMD [ "npm", "start" ]
